PUMATeam/catapult

- .gitignore
- ansible/roles/setup_host/playbook.yml
- ansible/roles/setup_host/tasks/build_firectl.yml
- ansible/roles/setup_host/tasks/compile.yml
- ansible/roles/setup_host/tasks/download.yml
- ansible/roles/setup_host/tasks/install.yml
- ansible/roles/setup_host/tasks/install_go.yml
- ansible/roles/setup_host/tasks/setup_firecracker.yml
- ansible/roles/setup_host/vars
- ansible/roles/start_vm/tasks/execute.yml
- tests/Vagrantfile
- tests/test_playbook.yml
- tests/vagrant_inventory
To run: ansible-playbook -i vagrant_inventory test_playbook.yml
TODO: 
- make the firecracker vm accessible
> start firecracker VM using ansible and vagrant

- README.md
> Add short project description to README

- util/util.go
if and error occured while executing
a cmd
> prevent the server from exiting

- ansible/roles/setup_host/tasks/build_catapult_node.yml
- ansible/roles/setup_host/tasks/files/start_catapult_node.sh
> catapult-node will not exit once ansible finishes

- pkg/model/model.go
no good reason to keep them separated
> consolidate models into a single file

- pkg/api/api.go
> add shutdown hooks

- Makefile
- ansible/roles/setup_host/tasks/build_catapult_node.yml
- db.test.toml
- internal/database/db.go
- pkg/api/host.go
- pkg/services/host.go
- pkg/services/host_test.go
- pkg/services/services.go
- pkg/util/util.go
> add basic host test

- tests/scripts/start_vm.sh
- tests/scripts/update_network.py
still not working properly though
> test networking improvements

- ansible/roles/setup_host/tasks/build_catapult_node.yml
- ansible/roles/setup_host/tasks/files/start_catapult_node.sh
- internal/database/migration/1_hosts.go
- pkg/api/host.go
- pkg/model/model.go
- pkg/node/service.go
- pkg/services/host.go
- pkg/util/ansible.go
- pkg/util/util.go
> support custom catapult-node port

- cmd/catapult/server.go
- docs/DESIGN.md
- pkg/api/api.go
- pkg/services/host.go
> Grpc shutdown

- docs/DESIGN.md
- pkg/model/model.go
- pkg/services/host.go
- pkg/services/vm.go
> Host initialization

- internal/database/db.go
Also it's worth to write unit test for `Connect()` but I cannot pass any argument into a function, so it's TODO for the future
> add connection check in Connect()

- README.md
- ansible/roles/setup_host/tasks/build_catapult_node.yml
fixes https://github.com/PUMATeam/catapult-node/issues/29
> set compilation target to linux

- pkg/node/node_connections.go
- pkg/services/host.go
> prevent grpc connection from timing out

- README.md
Just some minor changes to make the process of setting up the dev database more streamlined
> A nicer README for new devs

- ansible/roles/setup_host/tasks/setup_firecracker.yml
- pkg/services/host.go
and upgrade to latest firecracker
> fix download

- ansible/roles/setup_host/tasks/files/setup_bridge.sh
- ansible/roles/setup_host/tasks/setup_network.yml
> Update network script

- tests/scripts/create_test_vm.sh
> use virt-builder to create hypervisor image

- ansible/roles/setup_host/tasks/install_go.yml
- tests/scripts/create_test_vm.sh
> update go version

- ansible/roles/setup_host/tasks/files/setup_bridge.sh
Rather than hardcoding eth0 which is not necessarily correct.
Fixes #102
> detect host interface
